name = "femiknit"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
main = "worker.js"
assets = { binding = "ASSETS", directory = "build/client" }

[vars]
SUPABASE_URL = "https://ipkvytojvwszvdogvsmq.supabase.co"
SUPABASE_ANON_KEY = "sb_publishable_PHKu-TyI3me0aMswFvQYNA_iuATDfqR"
OWNER_EMAIL = "gamingwarlord8800@gmail.com"
APP_URL = "https://femiknit.vebmore.workers.dev"
